services:
  pbs:
    hostname: pbs
    container_name: pbs
    image: dockurr/proxmox-backup
    environment:
      TZ: "UTC"
      PASSWORD: "root"
    ports:
      - 8007:8007
    tmpfs:
      - /run
    volumes:
      - ./config:/etc/proxmox-backup
      - ./data:/var/lib/proxmox-backup
    restart: always
    stop_grace_period: 2m
