services:
  pbs:
    hostname: pbs
    container_name: pbs
    image: dockurr/proxmox-backup
    environment:
      PASSWORD: "root"
      TZ: "America/New_York"
    ports:
      - 8007:8007
    tmpfs:
      - /run
    volumes:
      - ./config:/etc/proxmox-backup
      - ./logs:/var/log/proxmox-backup
      - ./data:/var/lib/proxmox-backup
    restart: always
    stop_grace_period: 2m
